<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class ProductImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_images')->insert([
            [ 
               'image_path' => '/public/uploads/products/3/FsxiklEd4ZGzInk6xNFug9Ij7m3M4bZm.jpg',
               'image_name' => 'download.jpg',
               'product_id' => '1',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/Bg0vXdHc0SBH1IQi8pKy5f0skUs2NUpJ.jpg',
               'image_name' => 'download.jpg',
               'product_id' => '1',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/RHBr22QRcUQqDbI17ZUUlIT3YiEOVpnK.jpg',
               'image_name' => 'hinh3.jpg',
               'product_id' => '2',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/xgDOOBy6Adrwb6EIJnZJm2gZtcgsO4PD.jpg',
               'image_name' => 'hinh3.jpg',
               'product_id' => '2',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/iMIenCqfJwj8z52NSkog9rLNZcv8xJDl.jpg',
               'image_name' => 'hinh3.jpg',
               'product_id' => '2',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/hN9IPoJmMppQ93682nLaiOHIDw6aSY3u.jpg',
               'image_name' => 'image2.jpg',
               'product_id' => '3',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/wcItWCSKKsVKu74TwrdUNXgfVkOrageF.jpg',
               'image_name' => 'image2.jpg',
               'product_id' => '3',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/gSPkdCfLvkJPXxADnl8WUQfzIVNVxT7J.jpg',
               'image_name' => 'image2.jpg',
               'product_id' => '4',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/zZHIxmguFjCtohK0umGY3O6hUDaYoiPz.jpg',
               'image_name' => 'image2.jpg',
               'product_id' => '4',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/8JBSJ8MwS99TUgj9xATN3MREL7C6XSuX.jpg',
               'image_name' => 'image2.jpg',
               'product_id' => '4',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/qMmSxSwXe1BG5ZXg6mSh21jy6JlCMEh5.jpg',
               'image_name' => 'image4.jpg',
               'product_id' => '5',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/CHWGx0XksK3xgLVuO7yHTMbmtbh3fhoy.jpg',
               'image_name' => 'image4.jpg',
               'product_id' => '5',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/6ivEtLslvlUFDzjBmI9aCXMi8MCXGKsb.jpg',
               'image_name' => 'image4.jpg',
               'product_id' => '5',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/jJiDOB9WkSA797p62KDExB8Ik9OYyD1x.jpg',
               'image_name' => 'image4.jpg',
               'product_id' => '5',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/2mM68BSEKD1dPYbzTT2ZxDl3TjQADCfe.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '6',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/P0m3BSojs1f35Ry2kYIawVcv9wGij6GE.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '7',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/JT5bR71q9qFTmGKM0tzGYjqgUlCPwWId.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '7',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/UqnUeCRVzS56ZfiCuZ2IsOCqzDcrXxUO.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '8',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/EgJMtVAG8LD7tczsehoyhN7rznmEDA9c.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '8',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/hdgsYv1ObihNkt4SIzt6KIbXY8dAw9Vq.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '9',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/riyWRKUI07TmL8Pp6Fma0ajDQPJr8sMQ.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '9',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/opI0WBH8oEtmInMgTKq85NmhCRPKEAYh.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '10',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/CwJP81Pw7dKuhdWeWftG0wanM4jj9Dtv.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '10',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/IyjwlnyHjOJVTywXAkZ4KJ2C6rEUGy8y.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '11',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/fpOEmKzZdmFCviZoH4NrplC4EOI6C4qq.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '11',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/NwQyXONRNgosHHrcRCdjsPJBKJRG8z6m.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '12',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/0CvWL8saBXofDgzSV6Ox6EVWl8Nvskw6.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '12',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/ppwpV3AyNqhfa6fwAHnDrCxfU20YUeKY.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '13',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/u0i4VjZHj9fxDgLlDQ8VtL7MfTif3pwf.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '13',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/56RshlblEFkjdaQ0AfeGR676ZE93X5zS.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '14',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/IlM7iBPlEHV9RN9B1lf88APTnwMoDflr.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '14',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/ykCaO2ZSmBtC8vhSwSR7qLQ0OEak014o.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '14',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/yuRna3WY3YoTHUQVDOYVF5RiGFq3i2vi.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '14',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/2tOohvjvWbFBfBWIvZF4WRtHzARvWMAI.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '15',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/buTNxwxnof91DqZWq8sZSmlCMc9TxClt.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '15',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/OGsYqUHaWF1mtIHtGag0845MpIA5LgTn.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '15',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/h8h6DH1RqeztFWWd9XeskY5y5wFQKqRz.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '15',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/KUETrYesRwkklzUYpRRBjvJ4ekYLkOwz.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '16',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/c9g0ClFWvvIbcFWMzfc3iTmotFccj9WI.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '16',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/ZJ4lEbqCvUZBndTZPx8tew1sGhcjzSKr.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '16',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/t2FCXTBTHnBjs8uqFJJ57gTIbDpeZG2m.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '17',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/DeE6hUyyNGtXvGbGNP29pLKhD50N3i0q.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '18',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/LBxb1x0WTCUOUz4vkf2Cu4qcOTR2mso9.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '19',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
            [ 
               'image_path' => '/public/uploads/products/3/Wdux7V5duMnlAHqjbTyYehOHfypPZihu.jpg',
               'image_name' => 'img1.jpg',
               'product_id' => '20',
               'created_at' => Carbon::now(),
               'updated_at' => Carbon::now(),   
            ],
        ]);
    }
    }

